# Site settings:
site_title: 'Khepu'
site_description: 'Where I technologically vent'

# Profile:
name: 'Giorgos'
surname: 'Makris'
professional_identity: 'Software Engineer'
profile_picture: ''

# "About me" page's paragraphs:
about_me_paragraph: |

  If something seems interesting enough, I'll chase it down for the hell of it.

# Socials:
github_username: 'khepu'
github_icon: 'github.svg'

linkedin_username: 'giorgos-makris'
linkedin_icon: 'linkedin.svg'

# Email btn
email_address: ''

# "Buy me a coffee" button:
# buyMeACoffee_username: 'devnyxie'

# Other:
profile_picture_border: true
disable_about_me_page: false
disable_animated_underline: false
blog_preview_date_format: ''
blog_preview_date_separators: '-'
max_posts_per_page: '8'
